### ISSUE TITLE
Issues installing YAML ontologies in 3.4.1

### ISSUE THREAD

**Issue by CaptainHillman** [simphony/osp-core#522] opened 2020-09-16 11:21 UTC
I'm having issues installing the example YAML ontology provided by the SimDomeWrapper repository using OSP Core 3.4.1 (28247243b2d02cfd85b14d4ef12cf50cdd14432a). This is using Python 3.8.5 on Windows.

Note that the same YAML file installed correctly under OSP Core 3.3.8.

```
INFO 2020-09-16 12:11:12,695 [osp.core.ontology.yml.yml_parser]: You can now use "from osp.core.namespaces import simdome".
INFO 2020-09-16 12:11:12,695 [osp.core.ontology.parser]: Loaded 102 ontology triples in total
ERROR 2020-09-16 12:11:12,705 [osp.core.pico]: An Exception occurred during installation.
Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 788, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: "C:\\Users\\Michael\\AppData\\Local\\Temp\\tmpofq23_pr" -> "\\Users\\Michael\\.osp_ontologies\\graph.xml"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\michael\appdata\python-venvs\simdome\lib\site-packages\osp\core\pico.py", line 60, in install_from_terminal
    ontology_installer.install(*args.files)
  File "c:\users\michael\appdata\python-venvs\simdome\lib\site-packages\osp\core\ontology\installation.py", line 23, in install
    self._install(files, self._get_new_packages, False)
  File "c:\users\michael\appdata\python-venvs\simdome\lib\site-packages\osp\core\ontology\installation.py", line 139, in _install
    self.namespace_registry.store(self.path)
  File "c:\users\michael\appdata\python-venvs\simdome\lib\site-packages\osp\core\ontology\namespace_registry.py", line 133, in store
    self._graph.serialize(destination=path_graph, format="xml")
  File "c:\users\michael\appdata\python-venvs\simdome\lib\site-packages\rdflib\graph.py", line 982, in serialize
    shutil.move(name, path)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 261, in copyfile
    with open(src, "rb") as fsrc, open(dst, "wb") as fdst:
FileNotFoundError: [Errno 2] No such file or directory: "\\Users\\Michael\\.osp_ontologies\\graph.xml"
ERROR 2020-09-16 12:11:12,705 [osp.core.pico]: Consider running "pico --log-level debug install ..."
```

YAML file used: [simdome.ontology.yml.txt](https://github.com/simphony/osp-core/files/5231751/simdome.ontology.yml.txt)

**Comment by pablo-de-andres** [comment] 2020-09-17 07:20
have you tried running `pico --log-level debug install <path/to/ontology.yml>`? 
what is the output?

**Comment by pablo-de-andres** [comment] 2020-09-17 07:48
I am not able to reproduce the error. I would suggest trying the `--log-level debug` option first and otherwise reinstalling OSP-core clean, if possible

_Note:_ It looks like we forgot to increase the patch number in the release, I believe the version you are using is in fact 3.4.2

**Comment by CaptainHillman** [comment] 2020-09-17 09:28
- Running with debug logging produces the exact same stack trace
- Using the absolute path to the yml file seems to make no change
- Removing OSP core and PICO from pip then rebuilding them also produces no change

**Comment by pablo-de-andres** [comment] 2020-09-17 09:41
Could you open a python command line
```py
import os; os.path.join(os.path.expanduser("~"), ".osp_ontologies")
```
I don't really understand why yours is missing the `C:`

**Comment by CaptainHillman** [comment] 2020-09-21 12:00
This give the expected (correct) response.

`"C:\Users\Michael\.osp_ontologies"`

If I have some time this week I'll try to debug through the code, looking for anything that edits that path.

**Comment by pablo-de-andres** [comment] 2020-09-21 13:58
I believe @urbanmatthias (in charge of this code) is back tomorrow, so he should be able to give us a better insight!

**Comment by urbanmatthias** [comment] 2020-09-23 07:09
Hi,

thanks for reporting this issue. We are using the serialize method of rdflib to store the installed ontologies.
It looks like they internally store the graph in a temporary directory first `C:\\Users\\Michael\\AppData\\Local\\Temp\\tmpofq23_pr` and then they move it to the desired directory `\\Users\\Michael\\.osp_ontologies\\graph.xml`.

Obviously the second path is wrong - It should start with `C://`.

The path is decided in `osp/core/namespaces.py` in line 10:

```
_path = _os.path.join(
    _os.path.expanduser("~"),
    ".osp_ontologies"
)
```
which is the command you executed and which returned the correct path.

I also tried to reproduce it on my windows machine and failed.

Can you check if you have an outdated version of rdflib installed?

```
$ pip freeze | grep rdflib
rdflib==5.0.0
```

Can you print the `path_graph` at line 133 of `osp/core/ontology/namespace_registry.py`? 

```
self._graph.serialize(destination=path_graph, format="xml")
```

Can you print `_path` at line 14 of `osp/core/namespaces.py`? 

```
_os.makedirs(_path, exist_ok=True)
```

**Comment by urbanmatthias** [comment] 2020-09-23 07:17
Just as a side note, enabling debug log messages will almost always not change the traceback - but it might give us more information that can help us debugging. I'm afraid that in this case it wouldn't help much, because I didn't add any log messages that print the path. It probably would make sense to add some at the places I specified above. Anyway, maybe we have luck and there is something helpful in the logs, so could you please rerun with `--log-level debug` and paste the entire output here.

**Comment by urbanmatthias** [comment] 2020-09-23 07:31
Okay I just tried to reproduce on my windows machine but couldn't.

**Comment by CaptainHillman** [comment] 2020-09-23 12:02
I get the same version of rdflib as you (5.0.0), prints of the request variables are below.

path_graph from namespace_registry.py:
`C:\Users\Michael\.osp_ontologies\graph.xml`

_path from namespaces.py:
`C:\Users\Michael\.osp_ontologies`

I think I've found the line that's stripping the drive from the path though. RDFLIB's serialize function calls urlparse (from a version of the urllib library packaged within six I think), this appears to remove the drive. I can reproduce this with the following test code:

```
from urllib.parse import urlparse
import os

path = os.path.join(os.path.expanduser("~"), ".osp_ontologies")
print(path)

scheme, netloc, newpath, params, _query, fragment = urlparse(path)
print(newpath)
```

Which outputs:
```
C:\Users\Michael\.osp_ontologies
\Users\Michael\.osp_ontologies
```

**Comment by urbanmatthias** [comment] 2020-09-23 12:55
You are right, I see the line in rdflib and I have the same result when I execute the code you posted.

But it seems like leaving out the `C:` is not an issue on my machine. The following works:

```
shutil.move("setup.py", "\\Users\\urba\\.osp_ontologies\\setup.py")
```

Maybe you have multiple drives, and therefore shutil wants the user to specify it?
Can you check if the above works for you and whether the directory `C:\Users\Michael\.osp_ontologies` exists.

**Comment by urbanmatthias** [comment] 2020-09-23 13:28
I created a rdflib issue. Feel free to add anything you like: https://github.com/RDFLib/rdflib/issues/1170

**Comment by CaptainHillman** [comment] 2020-09-23 13:39
I do have multiple drives, this probably the likely cause.

The shutil.move() call does fail if no drive identifier is provided.

**Comment by urbanmatthias** [comment] 2020-09-23 13:54
Okay let's see if the rdflib guys answer, otherwise we'll either fork the repo or subclass the graph.

**Comment by urbanmatthias** [comment] 2020-09-25 09:05
Can you check if it works with this branch: https://github.com/urbanmatthias/rdflib/tree/patch-1

**Comment by CaptainHillman** [comment] 2020-09-25 15:24
This version of rdflib works like a charm, I can install my ontology successfully now.

Many thanks @urbanmatthias!

**Comment by urbanmatthias** [comment] 2020-10-14 16:08
I close this path, as the rdflib devs merged my pr: https://github.com/RDFLib/rdflib/pull/1172

**Closed** 2020-10-14 16:08 UTC
Labels: Windows OS, bug :bug:, pico

**Comment by dln22** [comment] 2021-02-16 15:06
Hello, I have just done a clean "osp-core" and "simcmclkinetics" wrapper install. It seems this issue is not fixed as I got the same error as Michael when I tried to install cmcl ontology via pico. As I understand the rdflib devs indicated that the issue is fixed on their side, maybe they forgot to merge it or we have a wrong rdflib version number set in the osp-core requirements file? When I re-installed everything I made sure that I purged conda and pip caches so that during installation pip was forced to download the rdflib from the remote PyPI repository rather than using the cached version. This did not help either.  Could you please advise?

**Comment by urbanmatthias** [comment] 2021-02-16 15:13
Hey, have you tried to install the latest rdflib master from source? I think the latest release does not contain the fix.

I agree that this should be documented on our side in an error message (or have another fix on our side that works with the latest rdflib master)

**Comment by dln22** [comment] 2021-02-16 15:21
Thanks Matthias, installing rdflib directly from its github source fixed the issue.
