### ISSUE TITLE
Switch websocket engine to increase performance

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#456] opened 2020-08-05 07:51 UTC
Concerning the performance of WebSocket in the transport session, Flask-SocketIo recommends using specific WebSocket engines to increase performance: https://flask-socketio.readthedocs.io/en/latest/#requirements
The relevant engines we could try:
- Eventlet: https://eventlet.net/doc/modules/websocket.html
- Gevent: https://github.com/jgelens/gevent-websocket

@aaronAB1993 @urbanmatthias

**Comment by urbanmatthias** [comment] 2020-08-05 08:17
As far as I understood @aaronAB1993 the main problem is not websockets but rather serialization. Do you habe any idea how we could increase serialization performance?

**Comment by urbanmatthias** [comment] 2020-08-05 08:19
The problem is we iterate over all cuds objects in the buffer and then over all the relationships and attributes of each cuds object. And I think this iteration simply takes time in python if there are a lot of objects.

**Comment by urbanmatthias** [comment] 2021-03-17 07:53
Do these engines support compression?

**Comment by yoavnash** [comment] 2021-03-17 09:14
Don't know, but I imagine they do.
What about the idea of moving to HTTP altogether? Does it have any value?

**Comment by urbanmatthias** [comment] 2021-03-17 09:16
Yes probably moving to HTTP is the best option.....
Then I'll close this issue.

**Closed by urbanmatthias** 2021-03-17 09:16 UTC

**Comment by yoavnash** [comment] 2021-03-17 10:39
Is it described in the SimPhoNy v4 doc?

**Comment by urbanmatthias** [comment] 2021-03-17 11:59
It is described in the SimPhony documentation for contributors file in the owncloud

**Comment by yoavnash** [comment] 2021-03-17 12:44
What are the advantages of changing to HTTP now that it's not so relevant for the MarketPlace? I don't see it there.

**Comment by urbanmatthias** [comment] 2021-03-17 13:04
ReST:
![image](https://user-images.githubusercontent.com/42069939/111471724-7ddd5c00-8729-11eb-8dd2-19275ea4428b.png)
Compression:
![image](https://user-images.githubusercontent.com/42069939/111471773-8afa4b00-8729-11eb-8519-dafb82896a6d.png)

Should there be any more info? Not sure if there are any more benefits for switching to HTTP other than that

**Comment by yoavnash** [comment] 2021-03-18 09:14
I'm not sure that I agree, but I think that it's good that it's there so we could think about it later. Thanks.
