### ISSUE TITLE
Allow specification of all functional relationships in constructor, not only data attributes

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#275] opened 2020-06-22 14:14 UTC
In GitLab by @urbanmatthias on Mar 16, 2020, 11:48

maybe we could specify an alias if a functional relationship is used in the constructor.

That is:
```
temperature = emmo.temperature(value=200)
temperature.add(qudt.celsius, rel=emmo.hasUnit)
```
is equivalnet to
```
temperature = emmo.temperature(value=200, hasUnit=qudt.celsius)
```
which is equivalnet to
```
temperature = emmo.temperature(value=200, unit=qudt.celsius)
```

Two different way to generate that alias automatically:

- remove "has" of "hasUnit"
- use range of hasUnit, which would be unit

In both cases the namespace will not be specified.

**Comment by urbanmatthias** [comment] 2020-08-05 07:16
Duplicate of #416

**Closed by urbanmatthias** 2020-08-05 07:16 UTC
Labels: api details, discussion
