### ISSUE TITLE
Problem with default attributes

### ISSUE THREAD

**Issue by paulzierep** [simphony/osp-core#693] opened 2021-08-13 14:16 UTC
EMMO has default values, e.g. for Milli:
Protege: "Milli hasSymbolData value "m""

```
###  http://emmo.info/emmo/middle/siunits#EMMO_a3a701ed_6f7d_4a10_9aee_dfa1961fc7b7
<http://emmo.info/emmo/middle/siunits#EMMO_a3a701ed_6f7d_4a10_9aee_dfa1961fc7b7> rdf:type owl:Class ;
                                                                                 rdfs:subClassOf <http://emmo.info/emmo/middle/siunits#EMMO_471cb92b_edca_4cf9_bce8_a75084d876b8> ,
                                                                                                 [ rdf:type owl:Restriction ;
                                                                                                   owl:onProperty [ owl:inverseOf <http://emmo.info/emmo/middle/math#EMMO_3446e167_c576_49d6_846c_215bb8878a55>
                                                                                                                  ] ;
                                                                                                   owl:allValuesFrom [ rdf:type owl:Restriction ;
                                                                                                                       owl:onProperty <http://emmo.info/emmo/middle/math#EMMO_faf79f53_749d_40b2_807c_d34244c192f4> ;
                                                                                                                       owl:hasValue 1e-3
                                                                                                                     ]
                                                                                                 ] ,
                                                                                                 [ rdf:type owl:Restriction ;
                                                                                                   owl:onProperty <http://emmo.info/emmo/middle/perceptual#EMMO_23b579e1_8088_45b5_9975_064014026c42> ;
                                                                                                   owl:hasValue "m"
                                                                                                 ] ;
                                                                                 <http://www.w3.org/2004/02/skos/core#prefLabel> "Milli"@en .

```

When trying to create the CUDS one has to add the hasSymbolData attribute, which is strange, since one does never want to change that data property. 

```
from osp.core.namespaces import siunits
siunits.Milli()
```

Error: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-df8b44165bd6> in <module>()
----> 1 siunits.Milli()

/home/paul/git/Fraunhofer/osp-core/osp/core/ontology/oclass.py in __call__(self, session, iri, uid, _force, **kwargs)
    298         # kwargs and defaults
    299         return Cuds(
--> 300             attributes=self._get_attributes_values(kwargs, _force=_force),
    301             oclass=self,
    302             session=session,

/home/paul/git/Fraunhofer/osp-core/osp/core/ontology/oclass.py in _get_attributes_values(self, kwargs, _force)
    227             elif not _force and obligatory:
    228                 raise TypeError("Missing keyword argument: %s" %
--> 229                                 attribute.argname)
    230             elif default is not None:
    231                 attributes[attribute] = default

TypeError: Missing keyword argument: hasSymbolData
```

**Comment by kysrpex** [comment] 2021-08-16 06:38
@paulzierep thanks for reporting it. 

Would you say that this is a showstopper (i.e. is very annoying to include the argument and later you'd want to remove it) that needs a hotfix as soon as possible (critical), or is it ok to have it fixed in the next stable release? I don't mind either way.

In any case, I leave this regex here for the future `hasSymbolData[\s\t\n]*=.*,[\s\t\n]*`, that will make deleting all unnecessary arguments a piece of cake.

**Comment by paulzierep** [comment] 2021-08-16 11:20
I don't think it is critical, since it can be bypassed by providing the default value. But I think correct handling of defaults is an important feature for the next stable release. 

And thanks for the regex !

**Comment by paulzierep** [comment] 2021-08-16 15:14
OK maybe there is a bit of a problem with this. If the hasSymbolData property has to be set,
the created data property assertion leads to inconsistency with the Fact++ reasoner. 

![factpluplus](https://user-images.githubusercontent.com/22075451/129586452-d7a77394-0c5e-4341-8ab0-f8287f38ff5d.jpg)

So I would say this behavior is breaking the support for EMMO (since Fact++  is teh default EMMO reasoner).

**Comment by kysrpex** [comment] 2021-08-17 05:48
> OK maybe there is a bit of a problem with this. If the hasSymbolData property has to be set,
> the created data property assertion leads to inconsistency with the Fact++ reasoner.
> 
> ![factpluplus](https://user-images.githubusercontent.com/22075451/129586452-d7a77394-0c5e-4341-8ab0-f8287f38ff5d.jpg)
> 
> So I would say this behavior is breaking the support for EMMO (since Fact++ is teh default EMMO reasoner).

Oh yeah I did not think of this, but I suffered this problem with OSP-core not setting the xsd:string part (with other statements rather than hasValue ones).

Ok, I add the critical label to release a hotfix instead.

**Comment by kysrpex** [comment] 2021-08-17 06:33
@paulzierep Sorry I just tried to replicate it and then remembered that it should be already solved on [v3.5.4-beta](https://github.com/simphony/osp-core/releases/tag/v3.5.4-beta) or later. Are you using such a version?

For the record, this seems to be a duplicate of #554.

**Comment by paulzierep** [comment] 2021-08-17 06:51
Ah yes, sorry I used 3.5.3.1; with 3.5.4 it's solved !

**Closed** 2021-08-17 06:54 UTC
Labels: :bug: bug, :scroll: ontology, :hammer: simple fix

**Comment by kysrpex** [comment] 2021-08-17 07:17
@paulzierep I advise you to use 3.5.5 (the newest one) though, in 3.5.4 ontology2dot is broken and is not compatible with rdflib 6 (which gives a performance boost).
