### ISSUE TITLE
Comments on yaml2camelcase

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#467] opened 2020-08-11 07:47 UTC
1. Namespaces under `requirements` remain in uppercase.
1. Suggestion: to make the file more readable, add spaces between classes.
1. Suggestion: keep the order of keywords as they appear in the original file
1. Unintuitive answer format for ambiguity resolution: 
![image](https://user-images.githubusercontent.com/62147380/89871395-a0b5f980-dbb7-11ea-9f8f-443255cb0658.png)

**Comment by yoavnash** [comment] 2020-08-11 07:55
![image](https://user-images.githubusercontent.com/62147380/89872133-cd1e4580-dbb8-11ea-97c7-199669b4e283.png)

**Comment by urbanmatthias** [comment] 2020-08-11 07:57
Yeah sorry for the inconvenience, this is a bug. yes should work

**Comment by yoavnash** [comment] 2020-08-11 07:58
I figure that it asks for every occurrence of that keyword. For the user, it's a bit weird.

**Comment by urbanmatthias** [comment] 2020-08-11 07:59
Ah I see

**Comment by urbanmatthias** [comment] 2020-08-11 07:59
Ok let me check

**Comment by urbanmatthias** [comment] 2020-08-11 08:07
See PR

**Comment by urbanmatthias** [comment] 2020-08-11 08:18
So after the first PR you already merged, the user should only be asked once per keyword.
The second fixes the issues with the requirements.

The other two would be hard to fix, because we are using the yaml library which does the serialization to file for us.,

**Comment by yoavnash** [comment] 2020-08-11 08:23
Alles klar

**Comment by urbanmatthias** [comment] 2020-08-11 08:29
What do you think of the behaviour, that if no output filename is given, it will replace the old one? And backs up the original in and .yml.orig file?

**Comment by yoavnash** [comment] 2020-08-11 08:34
I like it, for me it was convenient.

**Comment by yoavnash** [comment] 2020-08-11 08:46
Is it a convention that only concept classes begin with a capital case?
In that case, there seems to be some inconsistency:
![image](https://user-images.githubusercontent.com/62147380/89877020-c6470100-dbbf-11ea-9436-a539a58eb901.png)

Common ontology:
![image](https://user-images.githubusercontent.com/62147380/89877059-d5c64a00-dbbf-11ea-9d74-44f022f23b9c.png)

**Comment by urbanmatthias** [comment] 2020-08-11 08:48
This is the convention of OWL, that I adopted in the yaml2camelcase script

**Comment by urbanmatthias** [comment] 2020-08-11 08:49
It is followed by the EMMO people as far as I can tell:
```
    <owl:ObjectProperty rdf:about="http://emmo.info/emmo/middle/math#EMMO_3446e167_c576_49d6_846c_215bb8878a55">
        <rdfs:subPropertyOf rdf:resource="http://emmo.info/emmo/top/semiotics#EMMO_eb3518bf_f799_4f9e_8c3e_ce59af11453b"/>
        <rdfs:domain rdf:resource="http://emmo.info/emmo/middle/math#EMMO_54ee6b5e_5261_44a8_86eb_5717e7fdb9d0"/>
        <rdfs:range rdf:resource="http://emmo.info/emmo/middle/math#EMMO_1eed0732_e3f1_4b2c_a9c4_b4e75eeb5895"/>
        <rdfs:label xml:lang="en">hasVariable</rdfs:label>
    </owl:ObjectProperty>
```

**Comment by yoavnash** [comment] 2020-08-11 08:50
Then in the case above, there is an inconsistency, correct?

**Comment by urbanmatthias** [comment] 2020-08-11 08:51
Did it ask you if common.date is a class?

**Comment by urbanmatthias** [comment] 2020-08-11 08:52
Can you send me the file?

**Comment by yoavnash** [comment] 2020-08-11 08:52
I think it is, but the class `updateDate` doesn't start with a capital letter

**Comment by urbanmatthias** [comment] 2020-08-11 08:59
I cannot reproduce it ....

```
  UpdateDate:
    subclass_of:
    - common.Date
```

**Comment by urbanmatthias** [comment] 2020-08-11 09:00
(osp) urba@LAPTOP-ALEQPURM:/mnt/c/Users/urba/Desktop/ontologies$ yaml2camelcase metadata.ontology.yml -o output.yml
Is COMMON.DATE a ontology class (y/n)? yes
Is COMMON.VALUE a ontology class (y/n)? no
Is COMMON.LABEL a ontology class (y/n)? no

**Comment by yoavnash** [comment] 2020-08-11 09:01
Alright, let's ignore it. maybe I did something on the way

**Closed** 2020-08-11 09:03 UTC
